#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/live555ProxyServerEx
CONF=/etc/live555proxy.conf

start_service() {
    [ -f "$CONF" ] || return 1

    procd_open_instance
    # 执行命令及配置文件参数
    procd_set_param command $PROG -c $CONF
    # 异常崩溃后自动重启
    procd_set_param respawn
    # 自动将输出日志写入系统日志 (logread 可查)
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
